# Generated by Django 5.2.6 on 2025-10-03 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_deliveryaddress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "order_number",
                    models.PositiveBigIntegerField(editable=False, unique=True),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDIT_CARD", "Cartão de Crédito"),
                            ("DEBIT_CARD", "Cartão de Débito"),
                            ("BANK_SLIP", "Boleto Bancário"),
                            ("PIX", "Pix"),
                            ("CASH", "Dinheiro"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Pedido Recebido"),
                            ("PREPARATION", "Pedido em Preparação"),
                            ("DELIVERY", "Pedido em Entrega"),
                            ("WAITING_PAYMENT", "Aguardando Pagamento"),
                            ("DELIVERED", "Pedido Entregue"),
                            ("FINISHED", "Pedido Finalizado"),
                            ("CANCELED", "Pedido Cancelado"),
                        ],
                        default="RECEIVED",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.deliveryaddress",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="my_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
