# Generated by Django 5.2.6 on 2025-10-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryaddress",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="active",
            new_name="is_active",
        ),
    ]
