# Generated by Django 5.2.6 on 2025-10-22 00:31

from django.db import migrations, models


def create_order_sequence(apps, schema_editor):
    schema_editor.execute("CREATE SEQUENCE order_number_seq START 1 OWNED BY api_order.order_number;")
    schema_editor.execute(
        "ALTER TABLE api_order ALTER COLUMN order_number "
        "SET DEFAULT nextval('order_number_seq');"
    )

def drop_order_sequence(apps, schema_editor):
    schema_editor.execute("DROP SEQUENCE IF EXISTS order_number_seq;")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_product_image"),
    ]

    operations = [
        migrations.RunPython(create_order_sequence, reverse_code=drop_order_sequence),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.PositiveBigIntegerField(
                db_index=True, editable=False, unique=True
            ),
        ),
    ]
