# Generated by Django 5.2.6 on 2025-10-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.PositiveBigIntegerField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
    ]
