# Generated by Django 5.2.6 on 2025-10-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_order_order_number"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    ALTER TABLE api_order
                    ALTER COLUMN order_number
                    SET DEFAULT nextval('order_number_seq');
                """,
            reverse_sql="""
                    ALTER TABLE api_order
                    ALTER COLUMN order_number
                    DROP DEFAULT;
                """
        ),
    ]
