# Generated by Django 5.2.6 on 2025-10-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Pedido iniciado, mas ainda não submetido"),
                    ("PENDING", "Pedido submetido, porém ainda não confirmado"),
                    ("CONFIRMED", "Pedido confirmado"),
                    ("PREPARATION", "Pedido em Preparação"),
                    ("DELIVERY", "Pedido em Entrega"),
                    ("WAITING_PAYMENT", "Aguardando Pagamento"),
                    ("DELIVERED", "Pedido Entregue"),
                    ("FINISHED", "Pedido Finalizado"),
                    ("CANCELED", "Pedido Cancelado"),
                ],
                default="DRAFT",
                max_length=25,
            ),
        ),
    ]
