# Generated by Django 5.2.6 on 2025-11-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_orderitem_unique_product_per_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promotion",
            field=models.BooleanField(default=False),
        ),
    ]
